{
 "title": "Echo Framework Processes",
 "description": "Dashboard for applications that use https://github.com/globocom/echo-prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(echo_requests_total, app)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(echo_requests_total, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic - Req/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\"}[2m])) by (app,instance)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ app }} {{instance}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\"}[2m])) by (app, method,url)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ app }} - {{ method }} {{url}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "% Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\", code=~\"5\\\\d{2}\"}[5m])) by (app)/sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\"}[5m])) by (app)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "5xx - {{ app }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\", code=~\"4\\\\d{2}\"}[5m])) by (app)/sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\"}[5m])) by (app)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "4xx - {{ app }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "% Error per route",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\",code=~\"5\\\\d{2}\"}[5m])) by (app,url)/sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\"}[5m])) by (app,url)",
     "legendFormat": "5xx - {{ app }} - {{url}}"
    },
    {
     "expr": "sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\",code=~\"4\\\\d{2}\"}[5m])) by (app,url)/sum(rate(echo_requests_total{app=~\"$app\",instance=~\"$instance\"}[5m])) by (app,url)",
     "legendFormat": "4xx - {{ app }} - {{url}}"
    }
   ]
  },
  { "title": "Latêncy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Latency - General",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (app, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "P50 - {{ app }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (app, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "P95 - {{ app }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (app, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "P99 - {{ app }}"
    }
   ]
  },
  {
   "title": "Latency by handler",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (app, method,url,le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "P50 - {{ app }} - {{ method }} {{ url }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (app, method,url, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "P95 - {{ app }} - {{ method }} {{ url }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (app, method, url, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "P99 - {{ app }} - {{ method }} {{ url }}"
    }
   ]
  },
  {
   "title": "Latency by instance",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (app, instance, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "P50- {{ app }} - {{ instance }} ",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (app, instance, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "P95 - {{ app }} - {{ instance }} "
    },
    {
     "expr": "histogram_quantile(0.99, sum by (app, instance, le) (rate(echo_request_latency_seconds_bucket{app=~\"$app\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "P99 - {{ app }} - {{ instance }} "
    }
   ]
  }
 ]
}