{
 "title": "Keycloak Metrics",
 "description": "Monitoring keycloak metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(keycloak_logins,instance)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{instance=~\"$instance\",provider=\"keycloak\"},realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{instance=~\"$instance\",provider=\"keycloak\",realm=~\"$realm\"}, client_id)"
   },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(keycloak_request_duration_count{instance=~\"$instance\",app=\"keycloak\"}, route)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(keycloak_request_duration_bucket{instance=~\"$instance\",app=\"keycloak\"}, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{instance=~\"$instance\", area=\"heap\"})\n"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=~\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=~\"$instance\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "HTTP Errors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(keycloak_response_errors{instance=~\"$instance\",app=\"keycloak\",route=~\"$route\",method=~\"$method\"}[5m])",
     "legendFormat": "{{method}} - {{code}} - {{route}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,rate(keycloak_request_duration_bucket{instance=~\"$instance\",route=~\"$route\",method=~\"$method\"}[5m]))",
     "legendFormat": "P0.50 - {{method}} - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.9,rate(keycloak_request_duration_bucket{instance=~\"$instance\",route=~\"$route\",method=~\"$method\"}[5m]))",
     "legendFormat": "P0.90 - {{method}} - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99,rate(keycloak_request_duration_bucket{instance=~\"$instance\",route=~\"$route\",method=~\"$method\"}[5m]))",
     "legendFormat": "P0.99 - {{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "Logins per client on realm:$realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_logins{instance=~\"$instance\",provider=\"keycloak\",realm=~\"$realm\"}[5m])",
     "legendFormat": "{{realm}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Login Errors per client on realm:$realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts{instance=~\"$instance\",provider=\"keycloak\",realm=~\"$realm\"}[5m])",
     "legendFormat": "{{realm}} - {{client_id}} - {{error}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT on relm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations{instance=~\"$instance\",realm=~\"$realm\",provider=\"keycloak\"}[5m])",
     "legendFormat": "{{realm}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Registration Errors Per Client for realm:$realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations_errors{instance=~\"$instance\",provider=\"keycloak\",realm=~\"$realm\",client_id=~\"$ClientId\"}[5m])",
     "legendFormat": "{{realm}} - {{client_id}} - {{error}}"
    }
   ]
  }
 ]
}